= Glossary

== VL Component
A component is any delimited entity which is part of VL

== VL Document
Has a list of patches and a list of dependencies, that can be other VL Documents or Imports

== Root Document
A VL Document opened directly as opposed to being referenced as a Dependency of another VL Document

== Dependency
Reference to a VL Document, Import (.vlimport) or Dynamic-Link Library (.dll)

== Library
A file

== Import
A .json file that defines how an associated Dynamic-Link Library is being imported

== Patch
Short for _Utility Patch_ or _Datatype Patch_

== Utility Patch
Patch that defines one or more Functions. Can not contain Properties

== Datatype Patch
Patch that defines a datatype. Contains at least a _Create_ and an _Update_ method and may contain properties 

== Operation
Functionality defined via a graph of interconnected Nodes. Umbrella term for Function and Method

== Node
Short for either _Function Node_, _Method Node_ or _Process Node_

== Function Node
Node representing a call to an Operation defined in a Function Patch

== Method Node
Node representing a call to an Operation of a Datatype

== Process Node
Node that represents a fixed instance of a Datatype Patch

== Pin
Visual input or output element of a Node. Comparable to function argument or return parameter in other programming languages

== Link
Connection between two Pins. Comparable to a value assignment in other programming languages

== Inlet
Visual element in an Operation that represents an input parameter

== Outlet
Visual element in an Operation that represents a return parameter

== Property
Data-field of a Patch

== Setter	
Visual element in a Patch that writes to a Property

== Getter
Visual element in a Patch that reads from a Property

== Constant
Visual element in a Patch that allows for setting a constant value 

== Category
Feature of a Patch used to organize multiple patches into groups. Can be nested by separating multiple categories via a single dot. Comparable to the idea of a namespace in other programming languages

== Version
An identifier used to distinguish Patches or Operations in the same hierarchy that share the same name.

== Executable
A patch marked as being executable. Can be exported as .exe or used as a node in vvvv45

== Region
Visual element in a Patch which defines an area of a subgraph

== Loop Region
Calls the operation defined in its body _count_ times

== Foreach Region
Calls the operation defined in its body for each element in a collection. The current element is passed as inlet into the region body.

== If Region

== Spread
The default collection type

== Nuget

