= Glossary

== VL Component
Any entity that is part of VL, such as Document, Patch, Node, ...

== Identifier
An identifier is a text of one or more names that uniquely identifies a particular component in VL

== VL Document
A file ending in .vl that defines a range of patches and can have references to other VL Documents or managed .dlls

== Root Document
A VL Document opened directly as opposed to being referenced as a Dependency of another VL Document

== Dependency
Reference to a VL Document or managed Dynamic-Link Library (.dll)

== Library
A file that can be used as dependency. It contains a set of types and operations which are designed in a reusable and modular manner

== Patch
The blank canvas we can place nodes onto. There are different types of patches:

* Document Patch
* Datatype Patch 
* Group Patch 

== Group Patch
Helps to organise Node Definitions into groups. They can be cascaded and hold any number of Node Definitions. 

== Datatype 
The VL.CoreLib provides a range of primitive datatypes like Float32, String, RGBA, ... but VL also allows users to patch their own more complex datatypes, like e.g. a Particle consisting of properties like Position, Velocity, Color... Custom Datatypes can be immutable (Record) or mutable (Class). Both have their advantages and disadvantages:

* Record: use this one by default. it always keeps the dataflow, which keeps patches readable 
* Class: use only for advanced scenarios. allows to break the dataflow, good to patch more complex dependencies between datatypes, bad because it can make reading patches much harder

== Datatype Patch
Patch that defines a datatype. Contains at least a _Create_ and an _Update_ method and may contain Properties. Can be one of 3 types:

* Patch (default): to define a Process Node
* Record: to define an immutable datatype
* Class: to define a mutable datatype

== Record
A patch can be set to be a Record, meaning that it defines an immutable Datatype

== Class
A patch can be set to be a Class, meaning that it defines a mutable Datatype

== Operation
Functionality defined via a graph of interconnected Nodes. Synonymous for Function and Method

== Operations
Functionality defined via a graph of interconnected Nodes. Synonymous for Function and Method

== Node
Calls an operation defined in a Patch. There are _Function Nodes_, _Method Nodes_ and _Process Nodes_

== Nodes
Calls an operation defined in a Patch. 

== Node List
The list of available nodes in a VL Document as seen in the Node Browser. The list consists of all nodes defined in the VL Document itself as well as all nodes defined in the Dependencies of the document

== Process Node
Node that represents a fixed instance of a Datatype Patch. The term _process_ derives from the fact that we can imagine such a node running its own little process consisting at least of (but not limited to) the _Create_ operation that is evaluated once, the moment the node is created and the _Update_ operation that is "processing" each frame.

== State 
The state of an instance of a datatype comprises of the current values of all of its properties

== Pin
Visual input or output element of a Node. Comparable to function argument or return parameter in other programming languages

== Pins
Visual input or output element of a Node. Comparable to function argument or return parameter in other programming languages

== Pad
Visual elements to accesss Properties. Pads can be used to read from or write to Properties

== Pads
Visual elements to accesss Properties. Pads can be used to read from or write to Properties

== Link
Connection between two Pins. Comparable to a value assignment in other programming languages

== Links
Connection between two Pins. Comparable to a value assignment in other programming languages

== Inlet
Visual element in an Operation that represents an input parameter

== Outlet
Visual element in an Operation that represents a output parameter

== Field
Data-field of a Patch

== Fields
Data-field of a Patch

== Category
Feature of a Patch used to organize multiple patches into groups. Can be nested by separating multiple categories via a single dot. Comparable to the idea of a namespace in other programming languages

== Version
An identifier used to distinguish Patches or Operations in the same hierarchy that share the same name. 

== Executable
A patch marked as being executable. Can be exported as .exe or used as a node in vvvv45

== Region
Visual element in a Patch which defines an area of a subgraph

== Loop Region
Calls the operation defined in its body _count_ times

== Foreach Region
Calls the operation defined in its body for each element in a collection. The current element is passed as inlet into the region body.

== If Region
Executes the code in its body when the _Condition_ pin is true

== Spread
The default collection type

== Nuget

== Pascal Case
A casing convention that differentiates words in an identifier. Every first letter of a word in the identifier is capitalized. See: https://msdn.microsoft.com/en-us/library/ms229043.aspx[Capitalization Conventions]
