= VL - visual programming

An introduction to software development using VL.

VL is: 

* a visual programming language
* a development environment for the same
* a node and data type library

VL can

* compile and run code dynamically

VL is available as

* a package for vvvv

VL is targeted at developers who 

* prefer visual over textual code
* prefer interactive prototyping programming over edit/compile/fix error/compile/run
* are looking for data flow, object oriented and functional style programming metaphors 

We'll mainly be looking at things pure VL, and still see the differences to vvvv here and there. The focus yet is on explaining pure VL from the ground up, thus working as a guide for the still to upcoming standalone system. A special chapter will show how to integrate VL-nodes into your vvvv projects.

We are still in an early stage of carefully building the library. We'll give you an overview of what's there and how to solve problems you couldn't attack with vvvv. We'll highlight some known design patterns when things get bigger and show you how to modularize, break up patches and create you own basic building blocks by combining just a few nodes. We' ll explain some of the basic building blocks like TogEdge and S+H by looking at the patches defining them.

