# VL

= Overview

The most important components of VL are _nodes_ and _links_.

Nodes and links live on a canvas called _patch_.

One or multiple patches are contained in a VL Document. VL Documents are stored on hard disk.

Every patch can define one or more _operations_. Operations can be created as nodes in other patches.

There are two kinds of patches, one is merely a container for independent operations the other is a data type. If a patch is a data type its operations can store and/or share data via fields. Field can be accessed and/or modified in operations via _readers_ and __writers__.

One VL Document A can reference another VL file B to use its data types and operations. File B is then called a _dependency_ of A.

Patches can also contain _regions_. A region defines a new computational context. There are different kinds of regions.

Nodes and regions can have inputs and outputs calles _pins_. A pin can be defined in a patch or region by a _pad_.

Static data can be entered into an operation using _constants_. Constants are little editors for basic types like numbers, text, color…

Links transport data from outputs to inputs. Therefore they define the data flow and execution order of the nodes in an operation.

Each VL file can define one or more _executables_. Executables are patches which are the entry point of the program and can be started by a runtime.

