= Forwarding .NET Libraries

By link:/reference/libraries/using_net_libraries.adoc[Using .NET Libraries] we have direct access to a vast range of nodes for patching in VL. Many of those libraries though will not be very convenient to use in the dataflow context of VL. 

To make those libraries accessible to more casual users we often want to curate exactly what nodes and types of the original library are seen by them. Forwarding allows us to insert a very thin wrapper layer to conveniently provide such curation and do things like the following:

== Forwarding is used to
- Selectively forward types and operations of .NET .dlls
- Adjust VL relevant meta information on the types (like mutability and known type structure)
- Choose a relevant category for the nodes and types in VL
- Do simple type conversions (e.g. from angles in radians to angles in cycles)
- Rename pins, operations, types
- Set default values for input pins
- Provide convenience process nodes that wrap some low-level functionality into more high-level nodes
- Design lifetime management of disposables

.NOTE:
An important aspect when forwarding types from a library is that we don't want to introduce new wrapper-types. Therefore using Forwarding does not introduce new types! Forwarded types are compatible to the original library in order to allow users to still fall back to low-level functionality of the original library and combine that with the use of the high-level wrapper. 

TODO:

== Fowarding a Type
- place it in category/group
- dragdrop from solution explorer 
- create manually: forward, set type annotation
- rename type
- wildcard forwards all operations, vs. selective fwd
- mutability
- known type structure
- create default 
operations:
- rename pins
- set default 
- hide pins
- type conversions
- show category

== Forwarding Enums


== Forward Wrappers
In VL we can therefore say that a patch acts as a type-fowarding-wrapper or simply a 'Forward'. 

*Image:Set patch-type to 'Forward' and specify original type*

*Image:Type Foward*
Is Public: if you want to have this type show up for everyone referencing this document

What happens when the library changes
Use it to selectively expose stuff of your library to the user


=== Operation Forwards
*Image:Operation Foward*

Is Public: if you want to have this operation show up for everyone referencing this document

Show Category: if the “memberness” of the operation is important

Forward Pins

*Image:Renaming a Pin*

*Image:Hiding a Pin* usin an IOBox

*Image:Converting a type*

== Solution Explorer
Ctrl+M
Use the Solution Explorer to

- drop Type on the main patch -> creates a forward patch
- Drop member operations in type patch
- drop enum on main patch